const char *pars_lingue[5][5] = {
    {"Italiano", "Italian", "Italiano", "Italien", "Italienisch", },
    {"Inglese", "English", "Ingles", "Anglais", "Englisch", },
    {"Spagnolo", "Spanish", "Espanol", "Espagnol", "Spanisch", },
    {"Francese", "French", "Frances", "Francais", "Franzosisch", },
    {"Tedesco", "German", "Alemán", "Allemand", "Deutsch", },
};

const char *pars_loghi[6][5] = {
    {"Nessuno", "None", "Nadie", "Personne", "Niemand", },
    {"MS", "MS", "MS", "MS", "MS", },
    {"Lavenda", "Lavenda", "Lavenda", "Lavenda", "Lavenda", },
    {"Rotondi", "Rotondi", "Rotondi", "Rotondi", "Rotondi", },
    {"Schulthess", "Schulthess", "Schulthess", "Schulthess", "Schulthess", },
    {"Hoover", "Hoover", "Hoover", "Hoover", "Hoover", },
};

const char *pars_gettoniera[9][5] = {
    {"Nessuno", "None", "Ninguno", "Aucun", "Keine", },
    {"1 gettoniera NA", "1 Coint count. NO", "1 monedero NA", "1 accepteur de pieces NA", "1 NA-Munzprufer", },
    {"1 gettoniera NC", "1 Coin count. NC", "1 monedero NC", "1 monnayeur NC", "1 NC-Munzprufer", },
    {"2 gettoniere NA", "2 Coin count. NO", "2 monederos NA", "2 monnayeurs NA", "2 NA-Munzkasten", },
    {"2 gettoniere NC", "2 Coin count. NC", "2 monederos NC", "2 monnayeurs NC", "2 NC-Munzkasten", },
    {"Gettoniera digitale", "Digital coin count.", "Monedero digital", "Monnayeur numerique", "Digitaler Munzprufer", },
    {"G. dig. a linea singola", "D. c.c. single line", "Monedero digital de una linea", "Accepteur de pieces numerique a ligne unique", "Einzeiliger digitaler Munzprufer", },
    {"Cassa NA", "Cash Desk NA", "Maletin NA", "Caisse NA", "NA-Koffer", },
    {"Cassa NC", "Cash Desk NC", "Caja NC", "Caisse NC", "NC-Gehause", },
};

const char *pars_accelerometro[6][5] = {
    {"Disabilitato", "Deactivated", "Desactivado", "Desactive", "Deaktiviert", },
    {"1 velocita'", "1 speed", "1 velocidad", "1 vitesse", "1 Geschwindigkeit", },
    {"2 velocita'", "2 speed", "2 velocidades", "2 vitesses", "2 Geschwindigkeiten", },
    {"3 velocita'", "3 speed", "3 velocidades", "3 vitesses", "3 Geschwindigkeiten", },
    {"soglie delta", "delta thresh.", "Umbrales delta", "Seuils delta", "Delta-Schwellenwerte", },
    {"soglie HI", "HI thresh.", "Umbrales HI", "Seuils HI", "HI-Schwellenwerte", },
};

const char *pars_diretto_indiretto[2][5] = {
    {"Diretto", "Direct", "Directo", "Direct", "Direkt", },
    {"Indiretto", "Indirect", "Indirecta", "Indirect", "Indirekt", },
};

const char *pars_livello_accesso[4][5] = {
    {"Utente", "User", "Usuario", "Utilisateur", "Benutzer", },
    {"Tecnico", "Technician", "Tecnico", "Technicien", "Techniker", },
    {"Distributore", "Distributor", "Distribuidor", "Distributeur", "Vertriebspartner", },
    {"Costruttore", "Constructor", "Fabricante", "Fabricant", "Hersteller", },
};

const char *pars_ausiliari[8][5] = {
    {"Sblocco pagamento", "Unlocking payment", "Desbloqueo del pago", "Deblocage du paiement", "Entriegelung der Zahlung", },
    {"Standby saponi", "Soap standby", "Jabon en espera", "Savon en attente", "Seife in Bereitschaft", },
    {"Macchina occupata", "Machine busy", "Máquina ocupada", "Machine occupee", "Maschine besetzt", },
    {"Lampeggiante", "Flashing light", "Luz intermitente", "Lumiere clignotante", "Blinkendes Licht", },
    {"H2O recupero", "H2O recycling", "Recirculacion de H2O", "Recyclage H2O", "H2O Ruckfuhrung", },
    {"Pompa ricircolo", "Recirculation pump", "Bomba de recirculacion", "Pompe de recirculation", "Umwalzpumpe", },
    {"Scarico recupero", "Drain recovery", "Recuperacion de drenaje", "Recuperation des eaux usees", "Ruckgewinnung des Abflusses", },
    {"Riscald. indir.", "Indirect heating", "Calefaccion indirecta", "Chauffage indirect", "Indirekte Heizung", },
};

const char *pars_scala_accelerometro[6][5] = {
    {"0-2g con offset", "0-2g with offset", "0-2g con desviacion", "0-2g avec decalage", "0-2g mit offset", },
    {"1-4g con offset", "1-4g with offset", "1-4g con desviacion", "1-4g avec decalage", "1-4g mit offset", },
    {"2-8g con offset", "2-8g with offset", "2-8g con desviacion", "2-8g avec decalage", "2-8g mit offset", },
    {"3-2g no offset", "3-2g no offset", "3-2g sin desviacion", "3-2g sans decalage", "3-2g kein Offset", },
    {"4-4g no offset", "4-4g no offset", "4-4g sin desviacion", "4-4g sans decalage", "4-4g kein Offset", },
    {"5-8g no offset", "5-8g no offset", "5-8g sin desviacion", "5-8g sans decalage", "5-8g kein Offset", },
};

const char *pars_tipo_pagamento[5][5] = {
    {"Nessuno", "None", "Ninguno", "Aucun", "Keine", },
    {"Prezzo", "Price", "Precio", "Prix", "Preis", },
    {"Prezzo e rimanente", "Price and remaining", "Precio y resto", "Prix et reste", "Preis und Restbetrag", },
    {"Prezzo e credito", "Price and credit", "Precio y credito", "Prix et credit", "Preis und Kredit", },
    {"Rimanente e credito", "Remainder and credit", "Resto y credito", "Reste et credit", "Restbetrag und Gutschrift", },
};

const char *pars_tipo_livello[3][5] = {
    {"Centimetri", "Centimeters", "Centimetros", "Centimetres", "Zentimeter", },
    {"1 contalitri", "1 liter counter", "Contador de 1 litro", "Compteur de 1 litre", "1-Liter-Zahler", },
    {"2 contalitri", "2 liter counter", "Contadores de 2 litros", "Compteurs 2 litres", "2-Liter-Zahler", },
};

const char *pars_na_nc[2][5] = {
    {"Normalmente aperto", "Normally open", "Normalmente abierto", "Normalement ouvert", "Normalerweise offen", },
    {"Normalmente chiuso", "Normally closed", "Normalmente cerrado", "Normalement ferme", "Normalerweise geschlossen", },
};

const char *pars_rgb[8][5] = {
    {"Spento", "Off", "Apagado", "Arrêt", "Aus", },
    {"Blu", "Blue", "Azul", "Bleu", "Blau", },
    {"Verde", "Green", "Verde", "Vert", "Grun", },
    {"Azzurro", "Cyan", "Azul", "azur", "Azurblau", },
    {"Rosso", "Red", "Rojo", "Rouge", "Rot", },
    {"Viola", "Purple", "Morado", "Pourpre", "Lila", },
    {"Giallo", "Yellow", "Amarillo", "Jaune", "Gelb", },
    {"Bianco", "White", "Blanco", "Blanc", "Weiss", },
};

const char *pars_abilitazione[2][5] = {
    {"Disabilitato", "Deactivated", "Desactivado", "Desactive", "Deaktiviert", },
    {"Abilitato", "Activated", "Activado", "Active", "Aktiviert", },
};

const char *pars_tipo_serratura[4][5] = {
    {"Nuova/3/livello", "New/1/level", "Nuevo/3/nivel", "Nouveau/3/niveau", "Neu/3/Stufe", },
    {"Bobina/1/livello", "Reel/1/level", "Bobina/1/nivel", "Bobine/1/niveau", "Spule/1/Stufe", },
    {"Nuova/3/no livello", "New/3/no level", "Nuevo/3/sin nivel", "Nouveau/3/sans niveau", "Neu/3/keine Stufe", },
    {"Bobina/1/no livello", "Reel/1/no level", "Bobina/1/sin nivel", "Bobine/1/niveau", "Spule/1/keine Stufe", },
};

const char *pars_tipo_inverter[2][5] = {
    {"Avanti/indietro", "Forward/backward", "Avance/retroceso", "Avant/arriere", "Vorwarts/Ruckwarts", },
    {"Marcia/direzione", "Run/direction", "Avance/direccion", "Avant/direction", "Vorwarts/Richtung", },
};

const char *pars_nc_na[2][5] = {
    {"Normalmente chiuso", "Normally closed", "Normalmente cerrado", "Normalement ferme", "Normalerweise geschlossen", },
    {"Normalmente aperto", "Normally open", "Normalmente abierto", "Normalement ouvert", "Normalerweise offen", },
};

const char *pars_tempo_attivo[5][5] = {
    {"Subito", "Immediate", "Inmediatamente", "Immediatement", "Unmittelbar", },
    {"Dopo il livello", "After the level", "Despues del nivel", "Apres le niveau", "Nach Fullstand", },
    {"Dopo la temperatura", "After the temperature", "Despues de la temperatura", "Apres la temperature", "Nach der Temperatur", },
    {"Dopo liv. e temp.", "After lev. and temp.", "Despues de nivel y temperatura", "Apres le niveau et la temperature", "Nach Fullstand und Temperatur", },
    {"Con vel. di riempimento", "With fill speed", "Con velocidad de llenado", "Avec vitesse de remplissage", "Mit Fullgeschwindigkeit", },
};

const char *pars_richiesta_pagamento[4][5] = {
    {"Inserire gettone", "Insert token", "Insertar ficha", "Inserer un jeton", "Jeton einwerfen", },
    {"Inserire moneta", "Insert coin", "Insertar moneda", "Inserer une piece", "Munze einwerfen", },
    {"Pagamento cassa", "Pay at the desk", "Pago en efectivo", "Paiement en especes", "Barzahlung", },
    {"Pagamento importo", "Pay the required amount", "Importe del pago", "Montant du paiement", "Zahlungsbetrag", },
};

const char *pars_descriptions[169][5] = {
    {"PARAMETRO", "Parameter", "PARÁMETRO", "PARAMETRE", "PARAMETER", },
    {"LINGUA", "LANGUAGE", "IDIOMA", "LANGUE", "SPRACHE", },
    {"LOGO", "LOGO", "LOGO", "LOGO", "LOGO", },
    {"Nodo macchina", "Machine node", "Nodo máquina", "Noeud de la machine", "Maschinenknoten", },
    {"LIVELLO DI ACCESSO", "ACCESS LEVEL", "NIVEL DE ACCESO", "NIVEAU D'ACCES", "ZUGRIFFSEBENE", },
    {"TEMPO TASTO PAUSA", "PAUSE BUTTON TIME", "BOTON DE PAUSA TIEMPO", "DUREE DE LA TOUCHE PAUSE", "PAUSE-TASTE ZEIT", },
    {"TEMPO TASTO STOP", "STOP BUTTON TIME", "BOTON DE PARADA TIEMPO", "BOUTON D'ARRET TEMPS", "STOP-TASTE ZEIT", },
    {"TEMPO OUT PAGINE", "OUT PAGE TIME", "TIEMPO FUERA PÁGINAS", "TEMPS DE SORTIE PAGES", "TIME OUT SEITEN", },
    {"Durata", "Duration", "Duracion", "Duree de l'activite", "Dauer", },
    {"Tempo attivo", "Active time", "Tiempo activo", "Temps actif", "Aktive Zeit", },
    {"Moto in riempimento", "Fillup motion", "Marcha de llenado", "Mode de remplissage", "Fullgeschwindigkeit", },
    {"Velocita' riempimento", "Fillup speed", "Velocidad de llenado", "Vitesse de remplissage", "Geschwindigkeit der Befullung", },
    {"Inversione riempimento", "Fillup reversal", "Llenado inverso", "Remplissage inverse", "Fullen in umgekehrter Richtung", },
    {"T. moto riempimento", "Fillup motion time", "Tiempo de movimiento de llenado", "Temps de mouvement du remplissage", "Zeit der Fullbewegung", },
    {"T. pausa riempimento", "Fillup pause time", "Tiempo de pausa de llenado", "Temps de pause du remplissage", "Pausenzeit beim Fullen", },
    {"Velocita' lavaggio", "Wash speed", "Velocidad de lavado", "Vitesse de lavage", "Geschwindigkeit des Waschens", },
    {"Inversione lavaggio", "Wash reversal", "Lavado inverso", "Lavage en marche arriere", "Waschen Inversion", },
    {"T. moto lavaggio", "Wash motion time", "Tiempo de movimiento de lavado", "Temps de mouvement du lavage", "Bewegungszeit Waschen", },
    {"T. pausa lavaggio", "Wash pause time", "Tiempo de pausa de lavado", "Temps de pause du lavage", "Waschpausenzeit", },
    {"Riscaldamento", "Heating", "Calefaccion", "Chauffage", "Heizung", },
    {"Temperatura", "Temperature", "Temperatura", "Temperature d'utilisation", "Temperatur", },
    {"Tipo riscaldamento", "Heating type", "Tipo de calefaccion", "Type de chauffage", "Art der Heizung", },
    {"Tipo gettoniera", "Payment type", "Tipo de ficha", "Type de jeton", "Token-Typ", },
    {"Valore impulso", "Pulse value", "Valor de impulso", "Valeur de l'impulsion", "Impulswertigkeit", },
    {"Valore prezzo unico", "Absolute price value", "Valor de precio unico", "Valeur du prix unique", "Einzelpreiswert", },
    {"Prezzo unico", "Absolute price", "Precio unico", "Prix unique", "Einzelner Preis", },
    {"Cifre prezzo", "Price digits", "Digitos del precio", "Chiffres du prix", "Preis Ziffern", },
    {"Cifre decimali prezzo", "Decimal price digits", "Digitos decimales del precio", "Chiffres decimaux du prix", "Preis Dezimalziffern", },
    {"Visualizzazione prezzo", "Price display", "Visualizacion del precio", "Affichage du prix", "Preisanzeige", },
    {"Richiesta pagamento", "Payment request", "Solicitud de pago", "Demande de paiement", "Zahlungsanforderung", },
    {"Sblocco gettoniera", "Coin acc. unlock", "Liberacion de fichas", "Liberation du jeton", "Token-Freigabe", },
    {"Inibizione allarmi", "Disable alarms", "Inhibicion de alarma", "Inhibition de l'alarme", "Alarmverriegelung", },
    {"Diametro cesto", "Basket diameter", "Diámetro de la cesta", "Diametre du panier", "Korbdurchmesser", },
    {"Profondita' cesto", "Basked depth", "Profundidad de la cesta", "Profondeur du panier", "Tiefe des Korbes", },
    {"Altezza trappola", "Trap height", "Altura de la trampa", "Hauteur de la trappe", "Hohe des Auffangbehalters", },
    {"Sensore prossimita'", "Proximity sensor", "Sensor de proximidad", "Capteur de proximite", "Naherungsschalter", },
    {"Numero raggi", "Radiuses", "Numero de haces", "Nombre de faisceaux", "Anzahl der Strahlen", },
    {"Correzione contagiri", "Rounds corrector", "Correccion del tacometro", "Correction du tachymetre", "Tachometer-Korrektur", },
    {"Scala accelerometro", "Accelerometer scale", "Escala del acelerometro", "Echelle de l'accelerometre", "Skala des Beschleunigungsmessers", },
    {"Soglia x acc.", "Acc. x limit", "Umbral x acelerometro", "Accelerometre x a seuil", "Schwellenwert x-Beschleunigungsmesser", },
    {"Soglia y acc.", "Acc. y limit", "Umbral y acelerometro", "Seuil accelerometre y", "Schwellenwert y-Beschleunigungsmesser", },
    {"Soglia z acc.", "Acc. z limit", "Umbral z acelerometro", "Seuil z accelerometre", "Schwellenwert z-Beschleunigungsmesser", },
    {"Soglia x acc. (h)", "Acc. x limit (h)", "Umbral x acelerometro (h)", "Seuil accelerometre x (h)", "Schwellenwert x-Beschleunigungsmesser (h)", },
    {"Soglia y acc. (h)", "Acc. y limit (h)", "Umbral y acelerometro (h)", "Seuil y accelerometre (h)", "Schwellenwert y-Beschleunigungsmesser (h)", },
    {"Soglia z acc. (h)", "Acc. z limit (h)", "Umbral z acelerometro (h)", "Seuil accelerometre z (h)", "Schwellenwert z-Beschleunigungsmesser (h)", },
    {"Soglia accelerometro", "Accelerometer limit", "Umbral acelerometro", "Seuil accelerometre", "Schwellenwert Beschleunigungsmesser", },
    {"Soglia accelerometro 2", "Accelerometer limit 2", "Umbral acelerometro 2", "Seuil accelerometre 2", "Schwellenwert Beschleunigungsmesser 2", },
    {"Delta accelerometro", "Delta accelerometer", "Delta del acelerometro", "Accelerometre delta", "Beschleunigungsmesser delta", },
    {"Tempo attesa acc.", "Acc. wait time", "Tiempo de espera del acelerometro", "Temps d'attente de l'accelerometre", "Beschleunigungsmesser Wartezeit", },
    {"Temperatura massima", "Maximum temperature", "Temperatura máxima", "Temperature maximale", "Hochsttemperatur", },
    {"Isteresi temperatura", "Temperature hysteresis", "Histeresis de temperatura", "Hysteresis de temperature", "Temperatur-Hysterese", },
    {"Temperatura sicurezza", "Safety temperature", "Temperatura de seguridad", "Temperature de securite", "Sicherheitstemperatur", },
    {"Temperatura termodegradazione", "Thermal degradation temperature", "Temperatura de termodegradacion", "Temperature de thermodegradation", "Temperatur der thermischen Zersetzung", },
    {"Tipo livello", "Level type", "Tipo de nivel", "Type de niveau", "Niveau-Typ", },
    {"Tempo isteresi livello", "Level hysteresis time", "Tiempo de histeresis de nivel", "Temps d'hysteresis du niveau", "Pegel-Hysteresezeit", },
    {"Livello massimo", "Max level", "Nivel máximo", "Niveau maximum", "Maximaler Fullstand", },
    {"Livello sfioro", "Touch level", "Nivel de desbordamiento", "Niveau de debordement", "Uberlaufniveau", },
    {"Livello minimo scarico", "Minimum drain level", "Nivel minimo de drenaje", "Niveau de vidange minimum", "Minimales Abflussniveau", },
    {"Livello minimo riscaldamento", "Minimum heating level", "Nivel minimo de calefaccion", "Niveau minimum de chauffage", "Minimales Heizungsniveau", },
    {"Litri massimi", "Maximum liters", "Litros máximos", "Lits maximums", "Maximale Liter", },
    {"Litri minimi riscaldamento", "Minimum heating liters", "Calentamiento minimo litros", "Chauffage minimum litres", "Minimale Heizleistung Liter", },
    {"Impulsi litri", "Pulses per liters", "Pulsos litros", "Impulsions litres", "Pulsierende Liter", },
    {"Tipo inverter", "Inverter type", "Tipo de inversor", "Type d'inverseur", "Inverter-Typ", },
    {"Velocita' servizio", "Service speed", "Velocidad de servicio", "Vitesse de service", "Betriebsgeschwindigkeit", },
    {"Velocita' minima lavaggio", "Minimum wash speed", "Velocidad minima de lavado", "Vitesse de lavage minimum", "Minimale Waschgeschwindigkeit", },
    {"Velocita' massima lavaggio", "Maximum wash speed", "Velocidad máxima de lavado", "Vitesse de lavage maximale", "Maximale Waschgeschwindigkeit", },
    {"Cicli preparazione", "Preparation cycles", "Ciclos de preparacion", "Cycles de preparation", "Aufbereitungszyklen", },
    {"T. marcia prep. rot.", "Run time rot. prep.", "Tiempo de preparacion de la rotacion", "Temps de fonctionnement de la preparation de la rotation", "Vorbereitungszeit der Rotation", },
    {"T. sosta prep. rot.", "Pause time rot. prep.", "Tiempo de preparacion de la rotacion", "Temps d'arrêt de la preparation de la rotation", "Verweilzeit fur die Vorbereitung der Rotation", },
    {"V. minima prep.", "Minimum prep. speed", "Velocidad minima de preparacion", "Vitesse de preparation minimale", "Min. Vorbereitungsgeschwindigkeit", },
    {"V. massima prep.", "Max prep. speed", "Velocidad máxima de preparacion", "Vitesse de preparation maximale", "Maximale Praparationsgeschwindigkeit", },
    {"V. min. centrifuga 1", "Minimum cen. 1 speed", "Velocidad min. de centrifugado 1", "Vitesse d'essorage minimale 1", "Min. Schleuderdrehzahl 1", },
    {"V. max centrifuga 1", "Maximum cen. 1 speed", "Velocidad máx. de centrifugado 1", "Vitesse d'essorage maximale 1", "Max. Schleuderdrehzahl 1", },
    {"V. min. centrifuga 2", "Minimum cen. 2 speed", "Velocidad min. de centrifugado 2", "Vitesse d'essorage minimale 2", "Min. Schleuderdrehzahl 2", },
    {"V. max centrifuga 2", "Maximum cen. 2 speed", "Velocidad máx. de centrifugado 2", "Vitesse d'essorage maximale 2", "Max. Schleuderdrehzahl 2", },
    {"V. min. centrifuga 3", "Minimum cen. 3 speed", "Velocidad min. de centrifugado 3", "Vitesse d'essorage min. 3", "Min. Schleuderdrehzahl 3", },
    {"V. max centrifuga 3", "Maximum cen. 3 speed", "Velocidad máx. de centrifugado 3", "Vitesse d'essorage max. 3", "Max. Schleuderdrehzahl 3", },
    {"T. minimo rampa", "Minium ramp time", "Tiempo minimo de rampa", "Temps de rampe minimum", "Min. Rampenzeit", },
    {"T. massimo rampa", "Maximum ramp time", "Tiempo de rampa máx.", "Duree maximale de la rampe", "Max. Rampenzeit", },
    {"N. max sbilanciamenti", "N. max sbilanciamenti", "Numero máx. de desequilibrio", "Nombre de desequilibres max.", "Max. Unwuchtzahl", },
    {"Min/sec", "Min/sec", "Min/seg", "Min/sec", "Min/Sek.", },
    {"Tipo serratura", "Lock type", "Tipo de bloqueo", "Type de blocage", "Art der Sperre", },
    {"Durata impulso serratura", "Lock pulse duration", "Duracion del impulso de bloqueo", "Duree de l'impulsion de verrouillage", "Dauer des Sperrimpulses", },
    {"Controllo t. continuo", "Continous t. control", "Control de tiempo continuo", "Controle du temps continu", "Kontinuierliche Zeitsteuerung", },
    {"Livello", "Level", "Nivel", "Niveau", "Pegel", },
    {"Ricircolo", "Recycling", "Recirculacion", "Recirculation", "Umwalzung", },
    {"Acqua fredda", "Cold water", "Agua fria", "Eau froide", "Kaltes Wasser", },
    {"Acqua calda", "Hot water", "Agua caliente", "Eau chaude", "Warmes Wasser", },
    {"Acqua depurata/recupero", "Purified/recovery water", "Agua depurada/recuperada", "Eau purifiee/recuperee", "Gereinigtes/zuruckgewonnenes Wasser", },
    {"Sapone", "Detergent", "Jabon", "Savon", "Seife", },
    {"Tempo sapone 1", "Detergent time 1", "Tiempo jabon 1", "Duree du savon 1", "Seife Zeit 1", },
    {"Ritardo sapone 1", "Detergent delay 1", "Tiempo de jabon 1", "Delai de savon 1", "Seife Verzogerung 1", },
    {"Tempo sapone 2", "Detergent time 2", "Tiempo de jabon 2", "Temps de savon 2", "Seife Zeit 2", },
    {"Ritardo sapone 2", "Detergent delay 2", "Retraso del jabon 2", "Delai de savon 2", "Seife Verzogerung 2", },
    {"Tempo sapone 3", "Detergent time 3", "Jabon Tiempo 3", "Temps de savon 3", "Seife Zeit 3", },
    {"Ritardo sapone 3", "Detergent delay 3", "Jabon Retraso 3", "Delai de savon 3", "Seife Verzogerung 3", },
    {"Tempo sapone 4", "Detergent time 4", "Jabon Tiempo 4", "Temps de savon 4", "Seife Zeit 4", },
    {"Ritardo sapone 4", "Detergent delay 4", "Jabon Retraso 4", "Delai de savon 4", "Seife Verzogerung 4", },
    {"Tempo sapone 5", "Detergent time 5", "Tiempo de jabon 5", "Temps de savon 5", "Seife Zeit 5", },
    {"Ritardo sapone 5", "Detergent delay 5", "Jabon Retraso 5", "Delai de savon 5", "Seife Verzogerung 5", },
    {"Tempo sapone 6", "Detergent time 6", "Tiempo de jabon 6", "Temps de savon 6", "Seife Zeit 6", },
    {"Ritardo sapone 6", "Detergent delay 6", "Retraso del jabon 6", "Delai de savon 6", "Seife Verzogerung 6", },
    {"Tempo sapone 7", "Detergent time 7", "Tiempo de jabon 7", "Temps de savon 7", "Seife Zeit 7", },
    {"Ritardo sapone 7", "Detergent delay 7", "Retraso del jabon 7", "Delai de savon 7", "Seife Verzogerung 7", },
    {"Tempo sapone 8", "Detergent time 8", "Tiempo de jabon 8", "Temps de savon 8", "Seife Zeit 8", },
    {"Ritardo sapone 8", "Detergent delay 8", "Retraso del jabon 8", "Delai de savon 8", "Seife Verzogerung 8", },
    {"Tempo sapone 9", "Detergent time 9", "Tiempo de jabon 9", "Temps de savon 9", "Seife Zeit 9", },
    {"Ritardo sapone 9", "Detergent delay 9", "Retraso del jabon 9", "Delai de savon 9", "Seife Verzogerung 9", },
    {"Tempo sapone 10", "Detergent time 10", "Tiempo de jabon 10", "Temps de savon 10", "Seife Zeit 10", },
    {"Ritardo sapone 10", "Detergent delay 10", "Retraso del jabon 10", "Delai de savon 10", "Seife Verzogerung 10", },
    {"Movimento", "Motion", "Movimiento", "Mouvement", "Bewegung", },
    {"Recupero", "Recovery", "Recuperacion", "Recuperation", "Erholung", },
    {"Tempo preparazione", "Preparation time", "Tiempo de preparacion", "Temps de preparation", "Vorbereitungszeit", },
    {"Preparation speed", "Preparation speed", "Velocidad de preparacion", "Vitesse de preparation", "Geschwindigkeit der Vorbereitung", },
    {"Tipo scarico", "Drain type", "Tipo de descarga", "Type de decharge", "Art der Entleerung", },
    {"Velocita' cen. 1", "Cen. speed 1", "Velocidad de centrifugado 1", "Vitesse de centrifugation 1", "Zentrifugengeschwindigkeit 1", },
    {"Tempo rampa 1", "Ramp time 1", "Tiempo de rampa 1", "Temps de rampe 1", "Rampenzeit 1", },
    {"Velocita' cen. 2", "Cen. speed 2", "Velocidad de centrifugado 2", "Vitesse de centrifugation 2", "Zentrifugendrehzahl 2", },
    {"Tempo rampa 2", "Ramp time 2", "Tiempo de rampa 2", "Duree de la rampe 2", "Rampenzeit 2", },
    {"Velocita' cen. 3", "Cen. speed 3", "Velocidad centrifuga 3", "Vitesse de centrifugation 3", "Zentrifugaldrehzahl 3", },
    {"Tempo rampa 3", "Ramp time 3", "Tiempo de rampa 3", "Temps de rampe 3", "Rampenzeit 3", },
    {"Tempo frenata", "Stop time", "Tiempo de frenado", "Temps de freinage", "Abbremszeit", },
    {"Tempo attesa", "Wait time", "Tiempo de espera", "Temps d'attente", "Wartezeit", },
    {"Tempo avviso attesa on", "Tempo avviso attesa on", "Tiempo de espera activado", "Temps d'attente active", "Wartezeit Warnzeit ein", },
    {"Tempo avviso attesa off", "Tempo avviso attesa off", "Tiempo de aviso de espera desactivado", "Temps d'attente et d'avertissement desactive", "Wartezeit Vorwarnzeit aus", },
    {"Numero rampe", "Ramp number", "Numero de rampa", "Nombre de rampes", "Rampennummer", },
    {"Tempo attivo sapone", "Detergent active time", "Tiempo activo de jabon", "Temps de savonnage actif", "Seife aktive Zeit", },
    {"T. attesa cen. 1", "Cen. 1 wait time", "Tiempo de espera centrifugadora 1", "Temps d'attente en centrifugeuse 1", "Zentrifuge Wartezeit 1", },
    {"T. attesa cen. 2", "Cen. 2 wait time", "Tiempo de espera centrifugado 2", "Temps d'attente en centrifugeuse 2", "Zentrifugenwartezeit 2", },
    {"Numero saponi", "Detergent count", "Numero de jabon", "Numero de savon", "Anzahl der Seifen", },
    {"Ritardo allarme livello", "Level alarm delay", "Retardo de alarma de nivel", "Retard de l'alarme de niveau", "Verzogerung Fullstandsalarm", },
    {"Ritardo allarme scarico", "Drain alarm delay", "Retardo de alarma de descarga", "Retard de l'alarme d'echappement", "Verzogerung Entleerungsalarm", },
    {"Ritardo micro oblo", "Door contact delay", "Retardo micro portilla", "Retard de l'alarme du hublot", "Verzogerung Porthole Micro", },
    {"Tempo precarica", "Preload time", "Tiempo de precarga", "Temps de precharge", "Vorladezeit", },
    {"Tempo pulizia saponi", "Soap cleaning time", "Tiempo de limpieza del jabon", "Temps de nettoyage du savon", "Seifenreinigungszeit", },
    {"Tempo carico saponi", "Soap load time", "Tiempo de carga del jabon", "Temps de chargement du savon", "Seifenladezeit", },
    {"Tempo colpo scarico", "Drain opening time", "Tiempo de descarga", "Duree de la course de decharge", "Entleerungshubzeit", },
    {"Tempo minimo scarico", "Minimum drain time", "Tiempo minimo de descarga", "Temps de dechargement minimum", "Minimale Entladezeit", },
    {"Tempo minimo frenata", "Minimum stop time", "Tiempo minimo de frenado", "Temps de freinage minimum", "Minimale Abbremszeit", },
    {"Scarico recupero", "Drain recovery", "Recuperacion de la descarga", "Recuperation de la decharge", "Erholung der Entladung", },
    {"Livello carico ridotto", "Reduced load level", "Nivel de carga reducido", "Niveau de charge reduit", "Reduzierter Fullstand", },
    {"Sapone carico ridotto", "Reduced load detergent", "Jabon de carga reducida", "Savon a charge reduite", "Reduzierte Lastseife", },
    {"Autoavvio", "Autostart", "Autoarranque", "Demarrage automatique", "Auto-Start", },
    {"Accelerometro", "Accelerometer", "Acelerometro", "Accelerometre", "Beschleunigungsmesser", },
    {"Tempo scarico accelerometro", "Accelerometer drain time", "Tiempo de descarga del acelerometro", "Temps de dechargement de l'accelerometre", "Beschleunigungsmesser-Entladezeit", },
    {"Tempo allarme temperatura", "Temperature alarm time", "Tiempo de alarma de temperatura", "Temps d'alarme de temperature", "Temperaturalarmzeit", },
    {"Espansione IO", "IO expansion", "Expansion IO", "Extension IO", "IO-Erweiterung", },
    {"Esclusione sapone", "Detergent exclusion", "Exclusion de jabon", "Exclusion du savon", "Ausschluss von Seife", },
    {"Macchina libera", "Machine free", "Máquina libre", "Machine libre", "Freie Maschine", },
    {"Tipo macchina libera", "Machine free signal", "Máquina tipo libre", "Type de machine libre", "Maschinentyp frei", },
    {"Tipo IN ausiliario 1", "Auxiliary IN type 1", "Auxiliar IN tipo 1", "Entree auxiliaire type 1", "Auxiliary IN Typ 1", },
    {"Tipo OUT ausiliario 2", "Auxiliary OUT type 2", "Auxiliar OUT tipo 2", "Auxiliaire OUT type 2", "Auxiliary OUT Typ 2", },
    {"Tipo OUT ausiliario 3", "Auxiliary OUT type 3", "Auxiliar OUT tipo 3", "Auxiliaire OUT type 3", "Hilfsausgang Typ 3", },
    {"Tipo OUT ausiliario 4", "Auxiliary OUT type 4", "Salida auxiliar tipo 4", "Sortie auxiliaire type 4", "Hilfsausgang Typ 4", },
    {"Lavaggio programmato", "Scheduled cycle", "Lavado programado", "Lavage programme", "Programmiertes Waschen", },
    {"LED da fermo", "LED while stopped", "LED en reposo", "LED a l'arrêt", "LED im Stillstand", },
    {"LED al lavoro", "LED while working", "LED en funcionamiento", "LED au travail", "LED bei der Arbeit", },
    {"LED in pausa", "LED in pause", "LED en pausa", "LED en pause", "LED pausiert", },
    {"LED in attesa", "LED waiting", "LED en espera", "LED en attente", "LED im Wartezustand", },
    {"LED con avviso", "LED with notification", "LED con aviso", "LED avec avertissement", "LED mit Warnung", },
    {"LED con allarme", "LED with alarmti", "LED con alarma", "LED avec alarme", "LED mit Alarm", },
    {"Interf. al lavoro", "Work interf.", "Interfaz en funcionamiento", "Interface en fonctionnement", "Schnittstelle in Betrieb", },
    {"Interf. da fermo", "Stopped interf.", "Interfaz en reposo", "Interface a l'arrêt", "Schnittstelle im Leerlauf", },
    {"Interf. menu'", "Menu interface", "Interfaz de menu", "Interface de menu", "Menu-Schnittstelle", },
    {"Velocita'", "Speed", "Velocidad", "Vitesse", "Geschwindigkeit", },
    {"Max programmi utente", "Max user programs", "Programas de usuario máx.", "Programmes utilisateur max.", "Max. Benutzerprogramme", },
    {"Ripetizione ciclo", "Cycle repetition", "Repeticion de ciclo", "Repetition du cycle", "Zykluswiederholung", },
    {"Interf. saponi", "Detergent interf.", "Interfaz de jabon", "Interface savon", "Seifenschnittstelle", },
    {"Tempo scarico servizio", "Service drain time", "Tiempo de drenaje de servicio", "Temps de vidange du service", "Service-Ablaufzeit", },
};

const char *pars_macchina_libera[3][5] = {
    {"Non gestita", "Not managed", "No gestionado", "Non gere", "Nicht verwaltet", },
    {"Commuta allo start", "Changes on start", "Cambio al inicio", "Commutation au demarrage", "Wechsel beim Start", },
    {"Commuta al pagamento", "Changes on payment", "Cambio en el momento del pago", "Commutation au moment du paiement", "Umschalten bei Zahlung", },
};

const char *pars_visualizzazione[2][5] = {
    {"Self", "Self", "Auto", "Autonome", "Selbst", },
    {"Laboratorio", "Laboratory", "Taller", "Atelier", "Werkstatt", },
};

