#ifndef AUTOGEN_FILE_PARS_H_INCLUDED
#define AUTOGEN_FILE_PARS_H_INCLUDED

typedef enum {
    PARS_LINGUE_ITALIANO = 0,
    PARS_LINGUE_INGLESE,
} pars_lingue_t;

extern const char *pars_lingue[2][2];
typedef enum {
    PARS_LOGHI_NESSUNO = 0,
    PARS_LOGHI_MS,
    PARS_LOGHI_LAVENDA,
    PARS_LOGHI_ROTONDI,
    PARS_LOGHI_SCHULTHESS,
    PARS_LOGHI_HOOVER,
} pars_loghi_t;

extern const char *pars_loghi[6][1];
typedef enum {
    PARS_GETTONIERA_NESSUNO = 0,
    PARS_GETTONIERA_GETT1_NA,
    PARS_GETTONIERA_GETT1_NC,
    PARS_GETTONIERA_GETT2_NA,
    PARS_GETTONIERA_GETT2_NC,
    PARS_GETTONIERA_GETT_DIG,
    PARS_GETTONIERA_GETT_DIG_SINGOLA,
    PARS_GETTONIERA_CASSA_NA,
    PARS_GETTONIERA_CASSA_NC,
} pars_gettoniera_t;

extern const char *pars_gettoniera[9][2];
typedef enum {
    PARS_TIPO_PAGAMENTO_NESSUNO = 0,
    PARS_TIPO_PAGAMENTO_PREZZO,
    PARS_TIPO_PAGAMENTO_PREZZO_E_RIMANENTE,
    PARS_TIPO_PAGAMENTO_PREZZO_E_CREDITO,
    PARS_TIPO_PAGAMENTO_RIMANENTE_E_CREDITO,
} pars_tipo_pagamento_t;

extern const char *pars_tipo_pagamento[5][2];
typedef enum {
    PARS_ABILITAZIONE_DISABILITATO = 0,
    PARS_ABILITAZIONE_ABILITATO,
} pars_abilitazione_t;

extern const char *pars_abilitazione[2][2];
typedef enum {
    PARS_RICHIESTA_PAGAMENTO_INSERIRE_GETTONE = 0,
    PARS_RICHIESTA_PAGAMENTO_INSERIRE_MONETA,
    PARS_RICHIESTA_PAGAMENTO_PAGAMENTO_CASSA,
    PARS_RICHIESTA_PAGAMENTO_PAGAMENTO_IMPORTO,
} pars_richiesta_pagamento_t;

extern const char *pars_richiesta_pagamento[4][2];
typedef enum {
    PARS_DESCRIPTIONS_PARAMETRO = 0,
    PARS_DESCRIPTIONS_LINGUA,
    PARS_DESCRIPTIONS_LOGO,
    PARS_DESCRIPTIONS_LIVELLO_ACCESSO,
    PARS_DESCRIPTIONS_TEMPO_TASTO_PAUSA,
    PARS_DESCRIPTIONS_TEMPO_TASTO_STOP,
    PARS_DESCRIPTIONS_DURATA,
    PARS_DESCRIPTIONS_TEMPO_ATTIVO,
    PARS_DESCRIPTIONS_MOTO_IN_RIEMPIMENTO,
    PARS_DESCRIPTIONS_VELOCITA_RIEMPIMENTO,
    PARS_DESCRIPTIONS_INVERSIONE_RIEMPIMENTO,
    PARS_DESCRIPTIONS_TEMPO_MOTO_RIEMPIMENTO,
    PARS_DESCRIPTIONS_TEMPO_PAUSA_RIEMPIMENTO,
    PARS_DESCRIPTIONS_VELOCITA_LAVAGGIO,
    PARS_DESCRIPTIONS_INVERSIONE_LAVAGGIO,
    PARS_DESCRIPTIONS_GIRO_LAVAGGIO,
    PARS_DESCRIPTIONS_PAUSA_LAVAGGIO,
    PARS_DESCRIPTIONS_RISCALDAMENTO,
    PARS_DESCRIPTIONS_TEMPERATURA,
    PARS_DESCRIPTIONS_TIPO_RISCALDAMENTO,
    PARS_DESCRIPTIONS_TIPO_GETTONIERA,
    PARS_DESCRIPTIONS_VALORE_IMPULSO,
    PARS_DESCRIPTIONS_VALORE_PREZZO_UNICO,
    PARS_DESCRIPTIONS_PREZZO_UNICO,
    PARS_DESCRIPTIONS_CIFRE_PREZZO,
    PARS_DESCRIPTIONS_CIFRE_DECIMALI_PREZZO,
    PARS_DESCRIPTIONS_VISUALIZZAZIONE_PREZZO,
    PARS_DESCRIPTIONS_RICHIESTA_PAGAMENTO,
    PARS_DESCRIPTIONS_SBLOCCO_GETTONIERA,
} pars_descriptions_t;

extern const char *pars_descriptions[29][2];

#endif
