const char *strings[101][2] = {
    {"", "", },
    {"Inserire moneta", "Insert coin", },
    {"Inserire gettone", "Insert token", },
    {"Pagare cassa", "Pay at desk", },
    {"Scelta programma", "Choose program", },
    {"e premere start", "and press start", },
    {"al  lavoro", "al  lavoro", },
    {"pausa lavoro", "pausa lavoro", },
    {"*  RAM   KO  *", "*  RAM   KO  *", },
    {"OBLO' APERTO", "OBLO' APERTO", },
    {"OBLO' SBLOCCATO", "OBLO' SBLOCCATO", },
    {"STOP EMERGENZA", "STOP EMERGENZA", },
    {"NO TEMPERATURA 1", "NO TEMPERATURA 1", },
    {"INVERTER KO", "INVERTER KO", },
    {"FILTRO  APERTO", "FILTRO  APERTO", },
    {"BLOCC.BRUCIATORE", "BLOCC.BRUCIATORE", },
    {"ALL.SONDA TEMP.1", "ALL.SONDA TEMP.1", },
    {"NO  ARIA", "NO  ARIA", },
    {"ANOMALIA  ARIA", "ANOMALIA  ARIA", },
    {"ANTIPIEGA  !", "ANTIPIEGA  !", },
    {"DRY  CONTROL", "DRY  CONTROL", },
    {"TEMPERATURA ALTA", "TEMPERATURA ALTA", },
    {"MANUTENZIONE !", "MANUTENZIONE !", },
    {"ITALIANO", "ITALIAN", },
    {"INGLESE", "ENGLISH", },
    {"CONTRASTO LCD", "LCD CONTRAST", },
    {"STATISTICHE", "STATISTICS", },
    {"Tempo accensione", "Active time", },
    {"Tempo lavoro", "Work time", },
    {"Tempo moto", "Run time", },
    {"Tempo ventilaz.", "Fan run time", },
    {"Tempo riscald.", "Heating time", },
    {"Cicli parziali", "Partial cycles", },
    {"Cicli totali", "Total cycles", },
    {"Gettoni totali", "Total coins", },
    {"Salvataggio in corso...", "Saving...", },
    {"TEMPO CICLO", "CYCLE TIME", },
    {"TEMPERATURA", "TEMPERATURE", },
    {"VELOCITA'", "SPEED", },
    {"LUNEDI'", "MONDAY", },
    {"MARTEDI'", "TUESDAY", },
    {"MERCOLEDI'", "WEDNESDAY", },
    {"GIOVEDI'", "THURSDAY", },
    {"VENERDI'", "FRIDAY", },
    {"SABATO", "SATURDAY", },
    {"DOMENICA", "SUNDAY", },
    {"MODIF. PROGRAMMA", "MODIFY PROG.", },
    {"Nessun programma", "No programs", },
    {"Crea un nuovo programma", "Create a new program", },
    {"PARAMETRI MAC.", "MAC. PARAMETERS", },
    {"PARAMETRI PASSO", "STEP PARAMETERS", },
    {"PREZZO", "PRICE", },
    {"Prezzo", "Price", },
    {"TIPO", "TYPE", },
    {"PASSI PROGRAMMA", "PROGRAM STEPS", },
    {"Passo", "Step", },
    {"Programma vuoto", "Empty program", },
    {"Ammollo", "Soaking", },
    {"Prelavaggio", "Prewash", },
    {"Lavaggio", "Washing", },
    {"Risciacquo", "Flushing", },
    {"Scarico", "Drain", },
    {"Centrifuga", "Centrifuge", },
    {"Srotolamento", "Unrolling", },
    {"Attesa operatore", "Waiting", },
    {"FASE", "PHASE", },
    {"Precarica in corso", "Preloading", },
    {"Attesa livello e temperatura", "Waiting for temperature and water level", },
    {"Attesa livello", "Waiting for the water level", },
    {"Attesa temperatura", "Waiting for temperature", },
    {"Riempimento", "Filling up", },
    {"Attesa termodegradazione", "Waiting for thermal breakdown", },
    {"Attesa livello scarico", "Waiting for drain level", },
    {"Prescarico", "Pre-draining", },
    {"Preparazione", "Preparing", },
    {"Raggiungimento velocità", "Reaching speed", },
    {"In frenata", "Stopping due to lurching", },
    {"Attesa frenata", "Waiting for full stop", },
    {"Scarico forzato", "Forced drain", },
    {"Recupero", "Recovery", },
    {"Uscita lavaggio", "Washing exit", },
    {"Pausa lavaggio", "Cycle pause", },
    {"Scarico necessario", "Drain required", },
    {"Molto sporchi con prelavaggio", "Very dirty with prewash", },
    {"Sportchi con prelavaggio", "Dirty with prewash", },
    {"Molto sporchi", "Very dirty", },
    {"Sporchi", "Dirty", },
    {"Colorati", "Coloured", },
    {"Sintetici", "Artificial", },
    {"Piumoni", "Duvets", },
    {"Delicati", "Delicates", },
    {"Lana", "Whool", },
    {"Lino e tendaggi", "Linen and curtains", },
    {"Centrifuga per delicati", "Centrifuge for delicates", },
    {"Sanificazione", "Sanification", },
    {"Errore EEPROM", "EEPROM error", },
    {"Allarme spegnimento", "Power off alarm", },
    {"Allarme comunicazione", "Communication alarm", },
    {"Allarme", "Alarm", },
    {"Cancellare il programma?", "Delete the program?", },
    {"Inizio programma", "Program start", },
};

