const char *strings[175][5] = {
    {"", "", "", "", "", },
    {"Inserire moneta", "Insert coin", "Insertar moneda", "Inserer une piece", "Munze einwerfen", },
    {"Inserire gettone", "Insert token", "Insertar ficha", "Inserer un jeton", "Jeton einwerfen", },
    {"Pagare cassa", "Pay cashier", "Pagar al cajero", "Payer le caissier", "Kassierer bezahlen", },
    {"Pagare gettone", "Pay token", "Pagar ficha", "Payer le jeton", "Jeton bezahlen", },
    {"Pagare moneta", "Pay coin", "Pagar moneda", "Payer la piece", "Munze bezahlen", },
    {"Scelta programma", "Select programme", "Seleccione el programa", "Selectionner le programme", "Programm auswahlen", },
    {"e premere start", "and press start", "y pulse Inicio", "et appuyer sur start", "und Start drucken", },
    {"al  lavoro", "at work", "al trabajo", "au travail", "bei der Arbeit", },
    {"pausa lavoro", "pause work", "pausar trabajo", "pause travail", "Arbeit unterbrechen", },
    {"*  RAM   KO  *", "* RAM KO", "* RAM KO", "* RAM KO", "* RAM KO", },
    {"OBLO' APERTO", "PORTHOLE OPEN", "PORTILLA ABIERTA", "PORTOLE OUVERT", "PORTHOLE OFFNEN", },
    {"OBLO' SBLOCCATO", "PORTHOLE UNLOCKED", "PORTILLA DESBLOQUEADA", "HUBLOT DEVERROUILLE", "BULLAUGE ENTRIEGELT", },
    {"STOP EMERGENZA", "EMERGENCY STOP", "PARADA DE EMERGENCIA", "ARRET D'URGENCE", "NOTHALT", },
    {"SBILANCIAMENTO", "UNBALANCING", "DESBLOQUEO", "DESEQUILIBRAGE", "AUSGLEICH", },
    {"CHIAVISTELLO BLOCCATO", "LOCK LOCKED", "CERRADURA BLOQUEADA", "VERROUILLAGE VERROUILLE", "SCHLOSS VERRIEGELT", },
    {"ALLARME SERRATURA", "LOCK ALARM", "ALARMA DE BLOQUEO", "ALARME DE VERROUILLAGE", "SCHLOSS ALARM", },
    {"ALLARME LIVELLO", "LEVEL ALARM", "ALARMA DE NIVEL", "ALARME DE NIVEAU", "NIVEAUALARM", },
    {"SERRATURA FORZATA", "LOCK FORCED", "BLOQUEO FORZADO", "VERROUILLAGE FORCE", "VERRIEGELUNG GEZWUNGEN", },
    {"NO TEMPERATURA", "NO TEMPERATURE", "SIN TEMPERATURA", "PAS DE TEMPERATURE", "KEINE TEMPERATUR", },
    {"INVERTER KO", "INVERTER KO", "INVERSOR KO", "INVERTER KO", "UMRICHTER KO", },
    {"FILTRO APERTO", "FILTER OPEN", "FILTRO ABIERTO", "FILTRE OUVERT", "FILTER OFFEN", },
    {"BLOCC.BRUCIATORE", "BURNER BLOCK", "BLOQUE QUEMADOR", "BLOCAGE DU BRULEUR", "BURNER BLOCK", },
    {"ALL.SONDA TEMP.", "ALL.TEMP. PROBE", "SONDA TODO.TEMP.", "SONDE ALL.TEMP.", "ALL.TEMP.FUHLER", },
    {"APERTO CON H2O", "OPEN WITH H2O", "ABIERTO CON H2O", "OUVERT AVEC H2O", "OFFEN MIT H2O", },
    {"ALLARME ACCELEROMETRO", "ACCELEROMETER ALARM", "ACELEROMETRO ALARMA", "ACCELEROMETRE ALARME", "BESCHLEUNIGUNGSMESSER ALARM", },
    {"ACC. FUORI SCALA", "ACC. OFF SCALE", "ACC. ESCALA OFF", "ACC. OFF SCALE", "ACC. AUS WAAGE", },
    {"ALLARME VELOCITA'", "SPEED ALARM", "ALARMA VELOCIDAD", "ALARME DE VITESSE", "GESCHWINDIGKEITSALARM", },
    {"NO MOTO", "NO MOTION", "NO MOVIMIENTO", "PAS DE MOUVEMENT", "KEINE BEWEGUNG", },
    {"NO FERMO", "NO STOP", "NO STOP", "PAS D'ARRET", "NICHT STOPP", },
    {"ALLARME TEMPERATURA", "TEMPERATURE ALARM", "ALARMA DE TEMPERATURA", "ALARME TEMPERATURE", "TEMPERATURALARM", },
    {"H2O IN VASCA", "H2O IN TANK", "H2O EN TANQUE", "H2O DANS LE RESERVOIR", "H2O IM TANK", },
    {"ALLARME RIEMPIMENTO", "FILLING ALARM", "ALARMA DE LLENADO", "ALARME DE REMPLISSAGE", "FULLUNGSALARM", },
    {"ALLARME RISC.", "HEAT ALARM", "ALARMA DE CALOR", "ALARME DE CHALEUR", "HEIZUNGSALARM", },
    {"ALLARME SCARICO", "DRAIN ALARM", "ALARMA DE DRENAJE", "ALARME DE VIDANGE", "ALARM ENTLEERUNG", },
    {"MACCHINA ACCESA", "MACHINE ON", "MÁQUINA ENCENDIDA", "MACHINE EN MARCHE", "MASCHINE AN", },
    {"NO  ARIA", "NO AIR", "NO AIRE", "PAS D'AIR", "KEINE LUFT", },
    {"ANOMALIA  ARIA", "AIR ANOMALY", "ANOMALIA AIRE", "ANOMALIE DE L'AIR", "LUFT ANOMALIE", },
    {"ANTIPIEGA  !", "DRY CONTROL !", "CONTROL SECO", "DRY CONTROL !", "TROCKENKONTROLLE !", },
    {"DRY  CONTROL", "DRY CONTROL", "CONTROL SECO", "DRY CONTROL", "TROCKENKONTROLLE", },
    {"TEMPERATURA ALTA", "HIGH TEMPERATURE", "ALTA TEMPERATURA", "TEMPERATURE ELEVEE", "HOHE TEMPERATUR", },
    {"MANUTENZIONE !", "MAINTENANCE !", "¡MANTENIMIENTO !", "MAINTENANCE !", "WARTUNG !", },
    {"ITALIANO", "ITALIAN", "ITALIANO", "ITALIEN", "ITALIENISCH", },
    {"INGLESE", "ENGLISH", "INGLES", "ANGLAIS", "ENGLISCH", },
    {"CONTRASTO LCD", "LCD CONTRAST", "LCD CONTRASTE", "CONTRASTE LCD", "LCD KONTRAST", },
    {"STATISTICHE", "STATISTICS", "ESTADISTICAS", "STATISTIQUES", "STATISTIKEN", },
    {"T acceso", "Active t.", "Tiempo de puesta en marcha", "Temps de demarrage", "Zeit der Inbetriebnahme", },
    {"T lavoro", "Work t.", "Tiempo de trabajo", "Temps de travail", "Betriebszeit", },
    {"T moto", "Run t.", "Tiempo de movimiento", "Temps de mouvement", "Bewegungszeit", },
    {"T ventilaz.", "Fan run time", "Tiempo de ventilacion", "Temps de ventilation", "Luftungszeit", },
    {"T risc.", "Heat time", "Tiempo de calentamiento", "Temps de chauffe", "Heizzeit", },
    {"Cicli par", "Part cycles", "Ciclos parciales", "Cycles partiels", "Teilweise Zyklen", },
    {"Cicli tot", "Tot cycles", "Ciclos totales", "Cycles totaux", "Gesamtzyklen", },
    {"Gettoni totali", "Total coins", "Total de fichas", "Total des jetons", "Token gesamt", },
    {"Salvataggio in corso...", "Saving...", "Ahorro en curso", "Memorisation en cours...", "Laufende Speicherung", },
    {"TEMPO CICLO", "CYCLE TIME", "TIEMPO DE CICLO", "TEMPS DU CYCLE", "ZYKLUSZEIT", },
    {"TEMPERATURA", "TEMPERATURE", "TEMPERATURA", "TEMPERATURE", "TEMPERATUR", },
    {"VELOCITA'", "SPEED", "VELOCIDAD", "VITESSE", "GESCHWINDIGKEIT", },
    {"LUNEDI'", "MONDAY", "LUNES", "LUNDI", "MONTAG", },
    {"MARTEDI'", "TUESDAY", "MARTES", "MARDI", "DIESTAG", },
    {"MERCOLEDI'", "WEDNESDAY", "MIERCOLES", "MERCREDI", "MITTWOCH", },
    {"GIOVEDI'", "THURSDAY", "JUEVES", "JEUDI", "DONNERSTAG", },
    {"VENERDI'", "FRIDAY", "VIERNES", "VENDREDI", "FREITAG", },
    {"SABATO", "SATURDAY", "SÁBADO", "SAMEDI", "SAMSTAG", },
    {"DOMENICA", "SUNDAY", "DOMINGO", "DIMANCHE", "SONNTAG", },
    {"MODIF. PROGRAMMA", "MODIFY PROG.", "MODIF. PROGRAMA", "MODIF. PROGRAMME", "ANDERUNG DES PROGRAMMS", },
    {"Nessun programma", "No programs", "Ningun programa", "Pas de programme", "Kein Programm", },
    {"Crea un nuovo programma", "Create a new program", "Crear un nuevo programa", "Creer un nouveau programme", "Erstellen Sie ein neues Programm", },
    {"PARAMETRI MAC.", "MAC. PARAMETERS", "PARÁMETROS MAC", "PARAMETRES DU MAC", "MAC-PARAMETER", },
    {"PARAMETRI PASSO", "STEP PARAMETERS", "PARÁMETROS DE PASO", "PARAMETRES DE L'ETAPE", "SCHRITT-PARAMETER", },
    {"PREZZO", "PRICE", "PRECIO", "PRIX", "PREIS", },
    {"Prezzo", "Price", "Precio", "Prix", "Preis", },
    {"TIPO", "TYPE", "TIPO", "TYPE", "TYP", },
    {"PASSI PROGRAMMA", "PROGRAM STEPS", "PROGRAMA PASOS", "PROGRAMME ETAPES", "PROGRAMM SCHRITTE", },
    {"Passo", "Step", "Paso", "Etape", "Schritt", },
    {"Programma vuoto", "Empty program", "Programa vacio", "Programme vide", "Programm entleeren", },
    {"Ammollo", "Soaking", "Remojo", "Trempage", "Einweichen", },
    {"Prelavaggio", "Prewash", "Prelavado", "Prelavage", "Vorwaschen", },
    {"Lavaggio", "Washing", "Lavar", "Lavage", "Waschen", },
    {"Risciacquo", "Flushing", "Aclarado", "Rincage", "Spulen", },
    {"Scarico", "Drain", "Escurrir", "Vidange", "Entleeren", },
    {"Centrifuga", "Centrifuge", "Centrifugadora", "Centrifugeuse", "Zentrifuge", },
    {"Srotolamento", "Unrolling", "Desenrollar", "Deroulement", "Abspulen", },
    {"Attesa operatore", "Waiting", "En espera del operario", "Operateur en attente", "Bediener wartet", },
    {"FASE", "PHASE", "FASE", "PHASE", "PHASE", },
    {"Precarica in corso", "Preloading", "Precarga en curso", "Prechargement en cours", "Vorbeladung im Gange", },
    {"Attesa livel. e temp.", "Wait for temper/level", "Esperando nivel y temp.", "Attente du niveau et de la temperature", "Warten auf Fullstand und Temp.", },
    {"Attesa livello", "Waiting for the water level", "Esperando nivel", "Attente du niveau", "Warten auf Fullstand", },
    {"Attesa temperatura", "Waiting for temperature", "Esperando temperatura", "Attente de la temperature", "Warten auf Temperatur", },
    {"Riempimento", "Filling up", "Llenado", "Remplissage", "Fullen", },
    {"Att.termodegradazione", "Wait for thermal down", "En espera de termodegradacion", "Thermodegradation en attente", "Standby-Thermoabbau", },
    {"Attesa livel. scarico", "Wait for drain level", "Esperando nivel de descarga", "Attente du niveau de decharge", "Warten auf Entladeniveau", },
    {"Prescarico", "Pre-draining", "Pre-descarga", "Pre-decharge", "Vor der Entleerung", },
    {"Preparazione", "Preparing", "Preparacion", "Preparation", "Vorbereitung", },
    {"Attesa velocita'", "Warning speed", "Velocidad de espera", "Vitesse d'attente", "Wartende Geschwindigkeit", },
    {"In frenata", "Stopping due to lurching", "Frenado", "Freinage", "Bremsen", },
    {"Attesa frenata", "Waiting for full stop", "Espera de frenado", "Freinage de l'attente", "Bremsen warten", },
    {"Scarico forzato", "Forced drain", "Descarga forzada", "Dechargement force", "Erzwungene Entladung", },
    {"Recupero", "Recovery", "Recuperacion", "Recuperation", "Wiederherstellung", },
    {"Uscita lavaggio", "Washing exit", "Salida de lavado", "Sortie de la chasse d'eau", "Spulen Ausgang", },
    {"Pausa lavaggio", "Cycle pause", "Pausa lavado", "Pause du lavage", "Pause Waschen", },
    {"Scarico necessario; tenere premuto il tasto stop", "Drain required; long press the stop button", "Descarga forzada; mantenga pulsado el boton de parada", "Dechargement necessaire ; maintenir le bouton d'arret", "Entladen erforderlich; Stopptaste gedruckt halten", },
    {"Molto sporchi con prelavaggio", "Very dirty with prewash", "Muy sucio con prelavado", "Tres sale avec prelavage", "Starke Verschmutzung mit Vorwaschgang", },
    {"Sportchi con prelavaggio", "Dirty with prewash", "Muy sucio con prelavado", "Tres sale avec prelavage", "Starke Verschmutzung mit Vorwaschgang", },
    {"Molto sporchi", "Very dirty", "Muy sucio", "Tres sale", "Stark verschmutzt", },
    {"Sporchi", "Dirty", "Sucio", "Sale", "Verschmutzt", },
    {"Colorati", "Coloured", "Colores", "Couleurs", "Buntes", },
    {"Sintetici", "Artificial", "Sinteticos", "Synthetiques", "Synthetik", },
    {"Piumoni", "Duvets", "Edredones", "Couettes", "Bettdecken", },
    {"Delicati", "Delicates", "Delicados", "Delicats", "Feinwasche", },
    {"Lana", "Whool", "Lana", "Laine", "Wolle", },
    {"Lino e tendaggi", "Linen and curtains", "Lino y cortinas", "Linge et rideaux", "Leinen und Gardinen", },
    {"Centrifuga per delicati", "Centrifuge for delicates", "Centrifugadora para prendas delicadas", "Centrifugeuse pour linge delicat", "Zentrifuge fur Feinwasche", },
    {"Sanificazione", "Sanification", "Desinfeccion", "Assainissement", "Desinfektion", },
    {"Errore EEPROM", "EEPROM error", "Error EEPROM", "Erreur EEPROM", "EEPROM-Fehler", },
    {"Allarme spegnimento", "Power off alarm", "Alarma de desconexion", "Alarme d'arret", "Abschalt-Alarm", },
    {"Allarme comunicazione", "Communication alarm", "Alarma de comunicacion", "Alarme de communication", "Kommunikationsalarm", },
    {"Allarme", "Alarm", "Alarma", "Alarme de communication", "Alarm", },
    {"Cancellare il programma?", "Delete the program?", "¿Borrar programa?", "Effacer le programme ?", "Programm loschen?", },
    {"Inizio programma", "Program start", "Iniciar programa", "Demarrer le programme", "Programm starten", },
    {"TEST LIVELLO", "LEVEL TEST", "NIVEL DE PRUEBA", "NIVEAU DE TEST", "TEST-EBENE", },
    {"Errore di comunicazione con la macchina", "Communication error with the machine", "Error de comunicacion con la máquina", "Erreur de communication avec la machine", "Kommunikationsfehler mit der Maschine", },
    {"Lingua videate", "Display language", "Idioma de la pantalla", "Langue de l'ecran", "Sprache des Bildschirms", },
    {"Lingua", "Language", "Idioma", "Langue de l'ecran", "Sprache", },
    {"INFORMAZIONI", "INFORMATIONS", "INFORMACION", "INFORMATION", "INFORMATIONEN", },
    {"Errore", "Error", "Error", "Erreur", "Fehler", },
    {"Abilitata", "Enabled", "Activado", "Active", "Aktiviert", },
    {"Si", "Yes", "Si", "Oui", "Ja", },
    {"No", "No", "No", "Non", "Nein", },
    {"Debug", "Debug", "Depurar", "Debogage", "Fehlersuche", },
    {"H2O cal", "Warm H2O", "H2O caliente", "H2O chaud", "H2O heiss", },
    {"H2O fre", "Cold H2O", "H2O frio", "H2O froid", "H2O kalt", },
    {"H2O flu", "Flux H2O", "Flujo de H2O", "H2O flow", "H2O Durchfluss", },
    {"H2O rec", "Rec H2O", "H2O rec", "H2O rec", "H2O rec", },
    {"Chiu. oblo", "Port close", "Cerrando portilla", "Fermeture du hublot", "Schauglas schliessen", },
    {"Aper. oblo", "Port open", "Abertura de portilla", "Ouverture du hublot", "Bullauge offnen", },
    {"T sap. 1", "T det. 1", "Tiempo jabon 1", "Temps de savonnage 1", "Seifenzeit 1", },
    {"T sap. 2", "T det. 2", "Tiempo jabon 2", "Temps de savonnage 2", "Seifenzeit 2", },
    {"T sap. 3", "T det. 3", "Tiempo jabon 3", "Temps de savonnage 3", "Seifenzeit 3", },
    {"T sap. 4", "T det. 4", "Tiempo jabon 4", "Temps de savonnage 4", "Seifenzeit 4", },
    {"T sap. 5", "T det. 5", "Tiempo jabon 5", "Temps de savonnage 5", "Seifenzeit 5", },
    {"T sap. 6", "T det. 6", "Tiempo jabon 6", "Temps de savonnage 6", "Seifenzeit 6", },
    {"T sap. 7", "T det. 7", "Tiempo jabon 7", "Temps de savonnage 7", "Seifenzeit 7", },
    {"T sap. 8", "T det. 8", "Tiempo jabon 8", "Temps de savonnage 8", "Seifenzeit 8", },
    {"T sap. 9", "T det. 9", "Tiempo jabon 9", "Temps de savonnage 9", "Seifenzeit 9", },
    {"T sap. 10", "T det. 10", "Tiempo jabon 10", "Temps de savonnage 10", "Seifenzeit 10", },
    {"FINE LAVAGGIO", "CYCLE END", "FIN LAVADO", "END WASH", "ENDE WASCHEN", },
    {"INIZIO LAVAGGIO", "CYCLE START", "INICIO LAVADO", "START WASH", "WASCHEN STARTEN", },
    {"LAV. INTERROTTO", "CYCLE STOPPED", "LAVADO PARAR", "LAVAGE ARRET", "WASCHEN STOPP", },
    {"APRIRE OBLO", "OPEN PORT", "AGUJERO ABIERTO", "OUVERTURE", "HOLLE OFFNEN", },
    {"STANDBY SAPONI", "DET. STANDBY", "JABON EN ESPERA", "SAVON EN RESERVE", "SEIFE STANDBY", },
    {"Inizio", "Start", "Inicio", "Demarrage", "Start", },
    {"Copiare in posizione", "Copy in position", "Copia en posicion", "Copie en position", "Kopie in Position", },
    {"Sapone", "Detergent", "Jabon", "Savon", "Seife", },
    {"TEST TEMPERATURE", "TEMPERATURES TEST", "TEST TEMPERATURA", "TEST DE TEMPERATURE", "TEMPERATURTEST", },
    {"TEST INGRESSI", "INPUT TEST", "PRUEBA DE ENTRADA", "TEST D'ENTREE", "EINGABE TEST", },
    {"TEST RISCALDO", "HEATING TEST", "PRUEBA DE CALOR", "TEST DE CHALEUR", "WARME TEST", },
    {"S. PROSSIMITA'", "PROXIMITY S.", "S. PROXIMIDAD", "S. PROXIMITE", "S. PROXIMITAT", },
    {"TEST CONTALITRI", "TEST L. COUNTER", "PRUEBA DE CAUDALIMETRO", "TEST DE DEBITMETRE", "DURCHFLUSSMESSER-TEST", },
    {"TEST MOTORE AVA", "TEST FORWARD", "PRUEBA MOTOR AVA", "TEST MOTEUR AVA", "AVA MOTOR TEST", },
    {"TEST MOTORE IND", "TEST BACKWARD", "PRUEBA MOTOR IND", "IND MOTEUR TEST", "IND MOTOR TEST", },
    {"TEST 0/10V", "TEST 0/10V", "TEST 0/10V", "TEST 0/10V", "0/10V TEST", },
    {"ARCHIVIAZIONE", "STORAGE", "ARCHIVO", "ARCHIVAGE", "ARCHIVIEREN", },
    {"Inserire un dispositivo di archiviazione", "Insert a storage device", "Insertar un dispositivo de almacenamiento", "Inserer un peripherique de stockage", "Einlegen eines Speichermediums", },
    {"Dispositivo rimosso; premere menu' per riavviare la macchina", "Device removed; press menu' to reset the machine", "Dispositivo retirado; pulse menu para reiniciar la máquina", "Peripherique retire ; appuyer sur menu pour redemarrer la machine", "Gerat entfernt; drucken Sie das Menu, um das Gerat neu zu starten", },
    {"Nessuna configurazione trovata", "No configuration found", "No se ha encontrado ninguna configuracion", "Aucune configuration trouvee", "Keine Konfiguration gefunden", },
    {"Chiave per esportare", "Key to export", "Clave para exportar", "Cle d'exportation", "Schlussel zum Exportieren", },
    {"Chiave per esportare - Bandiera per importare", "Key to export - Flag to import", "Clave para exportar - Bandera para importar", "Touche d'exportation - Drapeau d'importation", "Taste zum Exportieren - Flagge zum Importieren", },
    {"Configurazione esportata", "Configuration saved", "Configuracion exportada", "Configuration exportee", "Konfiguration exportiert", },
    {"Operazione in corso", "Processing", "Operacion en curso", "Operation en cours", "Vorgang lauft", },
    {"Configurazione caricata con successo", "Configuration successfully loaded", "Configuracion cargada correctamente", "Configuration chargee avec succes", "Konfiguration erfolgreich geladen", },
    {"Errore nel caricamento della configurazione", "Configuration load failed", "Error al cargar la configuracion", "Erreur de chargement de la configuration", "Fehler beim Laden der Konfiguration", },
    {"Errore nel salvataggio della configurazione", "Configuration save failed", "Error al guardar la configuracion", "Erreur de sauvegarde de la configuration", "Fehler beim Speichern der Konfiguration", },
    {"Aprire oblo' e svuotare cesto", "Open and empty ", "Portilla abierta y cesta vacia", "Ouvrir le hublot et vider le panier", "Bullauge offnen und Korb leeren", },
    {"Frenata in corso", "Stopping", "Frenado en curso", "Freinage en cours", "Bremsvorgang lauft", },
};

