const char *strings[55][2] = {
    {"Inserire moneta", "Insert coin", },
    {"Inserire gettone", "Insert token", },
    {"Pagare cassa", "Pay at desk", },
    {"Scelta programma", "Choose program", },
    {"al  lavoro", "al  lavoro", },
    {"pausa lavoro", "pausa lavoro", },
    {"CALDO", "HOT", },
    {"MEDIO", "WARM", },
    {"TIEPIDO", "LUKEWARM", },
    {"FREDDO", "COLD", },
    {"LANA", "WHOOL", },
    {"*  RAM   KO  *", "*  RAM   KO  *", },
    {"OBLO' APERTO", "OBLO' APERTO", },
    {"OBLO' SBLOCCATO", "OBLO' SBLOCCATO", },
    {"STOP EMERGENZA", "STOP EMERGENZA", },
    {"NO TEMPERATURA 1", "NO TEMPERATURA 1", },
    {"INVERTER KO", "INVERTER KO", },
    {"FILTRO  APERTO", "FILTRO  APERTO", },
    {"BLOCC.BRUCIATORE", "BLOCC.BRUCIATORE", },
    {"ALL.SONDA TEMP.1", "ALL.SONDA TEMP.1", },
    {"NO  ARIA", "NO  ARIA", },
    {"ANOMALIA  ARIA", "ANOMALIA  ARIA", },
    {"ANTIPIEGA  !", "ANTIPIEGA  !", },
    {"DRY  CONTROL", "DRY  CONTROL", },
    {"TEMPERATURA ALTA", "TEMPERATURA ALTA", },
    {"MANUTENZIONE !", "MANUTENZIONE !", },
    {"ITALIANO", "ITALIAN", },
    {"INGLESE", "ENGLISH", },
    {"CONTRASTO LCD", "LCD CONTRAST", },
    {"STATISTICHE", "STATISTICS", },
    {"Tempo accensione", "Active time", },
    {"Tempo lavoro", "Work time", },
    {"Tempo moto", "Run time", },
    {"Tempo ventilaz.", "Fan run time", },
    {"Tempo riscald.", "Heating time", },
    {"Cicli parziali", "Partial cycles", },
    {"Cicli totali", "Total cycles", },
    {"Gettoni totali", "Total coins", },
    {"Si e' verificato un malfunzionamento fatale della eeprom. I parametri non verranno caricati", "", },
    {"I parametri caricati dalla eeprom non erano validi. Sono stati corretti", "", },
    {"Salvataggio in corso...", "Saving...", },
    {"TEMPO CICLO", "CYCLE TIME", },
    {"TEMPERATURA", "TEMPERATURE", },
    {"VELOCITA'", "SPEED", },
    {"LUNEDI'", "MONDAY", },
    {"MARTEDI'", "TUESDAY", },
    {"MERCOLEDI'", "WEDNESDAY", },
    {"GIOVEDI'", "THURSDAY", },
    {"VENERDI'", "FRIDAY", },
    {"SABATO", "SATURDAY", },
    {"DOMENICA", "SUNDAY", },
    {"MODIF. PROGRAMMA", "MODIFY PROG.", },
    {"Nessun programma", "No programs", },
    {"Crea un nuovo programma", "Create a new program", },
    {"PARAMETRI MAC.", "MAC. PARAMETERS", },
};

