#ifndef HARDWAREPROFILE_H_INCLUDED
#define HARDWAREPROFILE_H_INCLUDED

#include "driver/gpio.h"

#define HAL_BUTTON_OUT_1 GPIO_NUM_1
#define HAL_BUTTON_OUT_2 GPIO_NUM_2
#define HAL_BUTTON_OUT_3 GPIO_NUM_3
#define HAL_BUTTON_OUT_4 GPIO_NUM_4
#define HAL_BUTTON_IN_1  GPIO_NUM_5
#define HAL_BUTTON_IN_2  GPIO_NUM_6
#define HAL_BUTTON_IN_3  GPIO_NUM_7
#define HAL_BUTTON_IN_4  GPIO_NUM_8

#define HAL_GETT_1 GPIO_NUM_9
#define HAL_GETT_2 GPIO_NUM_10
#define HAL_GETT_3 GPIO_NUM_11
#define HAL_GETT_4 GPIO_NUM_12
#define HAL_GETT_5 GPIO_NUM_13

#define HAL_GETT_INHIBIT GPIO_NUM_14

#define HAL_BUZZER GPIO_NUM_15

#define HAL_LED_RUN GPIO_NUM_46

#define HAL_DISPLAY_RETRO GPIO_NUM_34
#define HAL_DISPLAY_CS    GPIO_NUM_16
#define HAL_DISPLAY_RESET GPIO_NUM_17
#define HAL_DISPLAY_D     GPIO_NUM_18
#define HAL_DISPLAY_CLK   GPIO_NUM_19
#define HAL_DISPLAY_DOUT  GPIO_NUM_20

#define HAL_WRITE_PROTECT GPIO_NUM_39
#define HAL_I2C_SCL       GPIO_NUM_37
#define HAL_I2C_SDA       GPIO_NUM_38

#define HAL_MB_UART_TXD GPIO_NUM_26
#define HAL_MB_UART_RXD GPIO_NUM_21

#endif